"""CLI entrypoints.

`oncall init`           → scaffold ~/.oncall/.env on first install.
`oncall api`            → run the FastAPI orchestrator + HTTP API.
`oncall mcp`            → run the stdio MCP server (spawned by `claude` as a child).
`oncall telegram-login` → one-time Telegram userbot login.
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import secrets
import sys
from pathlib import Path


_STARTER_ENV = """\
# oncall-agent config. Generated by `oncall init`.
# Project-local .env (in cwd) overrides this file if both are present.

# Orchestrator
ONCALL_TOKEN={token}
ONCALL_PORT=8765
ONCALL_DB_PATH=~/.oncall/state.db
ONCALL_PROD_HOSTS=

# Deployment role.
#   (unset / "laptop") = legacy all-local mode: the executor uses its own
#       native Bash/Read/Edit/Write on THIS machine.
#   "server" = cloud-primary mode: this orchestrator runs on an always-on VPS;
#       the executor's native local tools are denied and local shell/file work
#       is routed to the user's laptop via the `mcp__oncall__laptop` proxy. The
#       laptop runs `oncall laptop-worker` (see below).
ONCALL_ROLE=
# Cloud-primary mode only. Shared secret authenticating the laptop worker's
# public long-poll routes. Generate with `openssl rand -hex 32`. Must match on
# the server (this file) and on the laptop worker's .env.
ONCALL_LAPTOP_TOKEN=
# Laptop worker → server base URL (e.g. https://oncall.example.com). Set this
# in the LAPTOP's .env (alongside ONCALL_LAPTOP_TOKEN) where you run
# `oncall laptop-worker`. The server ignores it.
ONCALL_SERVER_URL=

# Operator backend choice — see .env.example for details.
# Default uses Google AI Studio (gemini) with gemini-3.1-flash-lite for
# fast ack-first responses (~0.45s TTFA). Set to "vercel" if you need
# non-Google models via the AI Gateway.
ONCALL_OPERATOR_BACKEND=gemini
ONCALL_OPERATOR_MODEL=gemini-3.1-flash-lite
ONCALL_OPERATOR_REASONING_EFFORT=low

# Gemini (AI Studio) — required when ONCALL_OPERATOR_BACKEND=gemini.
# Get a key at https://aistudio.google.com/apikey
GEMINI_API_KEY=

# Vercel AI Gateway — used as the operator backend when
# ONCALL_OPERATOR_BACKEND=vercel.
# https://vercel.com/dashboard/ai-gateway/api-keys
AI_GATEWAY_BASE_URL=https://ai-gateway.vercel.sh/v1
AI_GATEWAY_API_KEY=

# Memory embedder runs via a local Ollama daemon. Pull the model first:
#   ollama pull nomic-embed-text:137m-v1.5-fp16
# embed calls send keep_alive=4h so Ollama keeps the model resident
# across `oncall service start` restarts.
ONCALL_MEMORY_EMBED_MODEL=nomic-embed-text:137m-v1.5-fp16
ONCALL_OLLAMA_HOST=http://localhost:11434

# Executor (Claude CLI) uses whatever auth `claude` already has on this host —
# keychain OAuth for subscription users, or ANTHROPIC_API_KEY in your shell env
# if you prefer a workspace API key. Nothing to configure here.

# Telegram — two userbot sessions sharing one application credential.
# 1. Register an application at https://my.telegram.org/apps to get
#    TELEGRAM_API_ID + TELEGRAM_API_HASH. Same credential drives both
#    sessions; they're distinguished by session file path.
# 2. PRIMARY userbot: runs on your own Telegram account. Reads inbound DMs
#    from third parties for triage + reply-on-your-behalf. Set up via:
#      oncall telegram-login
# 3. AGENT userbot: runs on a SECOND Telegram account dedicated to the
#    agent. This is the user-facing surface — you DM it, you call it
#    (future), approvals land here. Set up via:
#      oncall telegram-login --agent
# 4. Get your own numeric user_id from @userinfobot and paste it as
#    TELEGRAM_OWNER_USER_ID. The agent userbot only accepts messages
#    from that id.
TELEGRAM_API_ID=
TELEGRAM_API_HASH=
TELEGRAM_SESSION_PATH=~/.oncall/telegram.session
TELEGRAM_AGENT_SESSION_PATH=~/.oncall/telegram_agent.session
TELEGRAM_OWNER_USER_ID=
TELEGRAM_IMPORTANT_SENDERS=
TELEGRAM_IMPORTANT_KEYWORDS=urgent,down,production,outage,critical
# Comma-separated @usernames the primary userbot should NEVER surface
# (e.g. service bots like @userinfobot). The agent userbot's chat with
# the owner is filtered separately (by user_id, auto-discovered at
# `telegram-login --agent`).
TELEGRAM_USERBOT_IGNORE_USERNAMES=
"""


def _serve_api() -> None:
    import uvicorn
    from .config import get_settings
    from .api import create_app

    settings = get_settings()
    app = create_app()
    uvicorn.run(
        app,
        host=settings.oncall_bind_host,
        port=settings.oncall_port,
        log_level="info",
        # Cap how long uvicorn waits for in-flight connections on SIGTERM
        # before force-closing them and running lifespan teardown. Without
        # this, long-lived SSE subscribers to /events block teardown
        # indefinitely — and launchd's ExitTimeOut (default 20s) then
        # escalates to SIGKILL, skipping our shutdown path. Skipping
        # shutdown leaves pending approvals UNRESOLVED in the DB and lets
        # the next daemon boot try to --resume orphan claude sessions,
        # which fails with cli_error. Capping at 5s gives uvicorn enough
        # time to drain real traffic but guarantees lifecycle.shutdown()
        # runs (it denies pending approvals + marks running tasks killed).
        timeout_graceful_shutdown=5,
    )


def _serve_mcp() -> None:
    from .mcp_server import cli_main
    cli_main()


def _serve_laptop_worker() -> None:
    from .laptop_worker import cli_main
    cli_main()


def _init(*, force: bool = False) -> None:
    """Scaffold ~/.oncall/ with a starter .env. Safe to re-run; non-destructive."""
    config_dir = Path.home() / ".oncall"
    config_dir.mkdir(parents=True, exist_ok=True)
    env_path = config_dir / ".env"
    if env_path.exists() and not force:
        print(f"{env_path} already exists. Use --force to overwrite.")
        sys.exit(0)
    token = secrets.token_urlsafe(32)
    env_path.write_text(_STARTER_ENV.format(token=token), encoding="utf-8")
    env_path.chmod(0o600)
    print(f"Wrote {env_path} (mode 0600).")
    print("Next steps:")
    print(f"  1. Edit {env_path} — at minimum set AI_GATEWAY_API_KEY for the operator.")
    print("  2. Install Claude Code: https://docs.claude.com/en/docs/claude-code")
    print("  3. (Optional) `oncall telegram-login` to enable Telegram.")
    print("  4. `oncall api` to run the orchestrator.")


def _telegram_login(
    *, verbose: bool = False, qr: bool = False, agent: bool = False,
) -> None:
    from .config import (
        get_settings, write_telegram_agent_user_id,
    )
    from .telegram_service import login_interactive, login_qr_interactive

    s = get_settings()
    if not (s.telegram_api_id and s.telegram_api_hash):
        print("ERROR: set TELEGRAM_API_ID and TELEGRAM_API_HASH in .env first.", file=sys.stderr)
        print("  Get them at https://my.telegram.org/apps", file=sys.stderr)
        sys.exit(2)
    logging.getLogger("telethon").setLevel(logging.DEBUG if verbose else logging.INFO)
    session_path = s.telegram_agent_session_path if agent else s.telegram_session_path
    role = "AGENT" if agent else "PRIMARY"
    print(f"Logging in {role} Telegram session → {session_path}")
    if agent:
        print(
            "This must be a SEPARATE Telegram account from your primary "
            "(the userbot account that reads inbound DMs)."
        )
    runner = login_qr_interactive if qr else login_interactive
    user_id = asyncio.run(runner(
        api_id=int(s.telegram_api_id),
        api_hash=s.telegram_api_hash,
        session_path=session_path,
    ))
    print()
    print(f"Session written to {session_path}.")
    if agent:
        if user_id is None:
            print(
                "WARNING: couldn't read agent user_id after login. The primary "
                "userbot's peer filter for the agent chat won't be populated. "
                "Re-run `oncall telegram-login --agent` to retry."
            )
        else:
            write_telegram_agent_user_id(user_id)
            print(f"Agent user_id={user_id} written to ~/.oncall/telegram_agent_user_id.")
            print("The primary userbot will read this at next startup to skip "
                  "the agent chat in inbox-relay.")
    print()
    print("Next: restart the daemon to attach the new session:")
    print("  oncall service stop && oncall service start    (LaunchAgent)")
    print("  oncall api                                     (foreground / dev)")


def _configure_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    # Telethon is verbose at INFO — keep at WARNING unless explicitly opted in.
    logging.getLogger("telethon").setLevel(logging.WARNING)
    # SQLAlchemy / httpx are fine at WARNING too.
    logging.getLogger("httpx").setLevel(logging.WARNING)


def main() -> None:
    _configure_logging()
    parser = argparse.ArgumentParser(prog="oncall")
    sub = parser.add_subparsers(dest="cmd", required=True)
    init_p = sub.add_parser("init", help="Scaffold ~/.oncall/.env (run this first).")
    init_p.add_argument("--force", action="store_true",
                        help="Overwrite an existing ~/.oncall/.env.")
    sub.add_parser("api", help="Run the orchestrator HTTP API")
    sub.add_parser("mcp", help="Run the stdio MCP server (used by claude subprocesses)")
    sub.add_parser(
        "laptop-worker",
        help="Run the laptop capability worker (cloud-primary mode): long-polls "
             "the server for local shell/file jobs and runs them on this machine.",
    )
    tg_login_p = sub.add_parser(
        "telegram-login",
        help="One-time interactive Telegram userbot login (writes session file).",
    )
    tg_login_p.add_argument(
        "-v", "--verbose", action="store_true",
        help="Show telethon DEBUG logs (every MTProto frame) for troubleshooting.",
    )
    tg_login_p.add_argument(
        "--qr", action="store_true",
        help="Login via QR code instead of phone+code. Scan from an already-"
             "logged-in Telegram app (Settings → Devices → Link Desktop Device).",
    )
    tg_login_p.add_argument(
        "--agent", action="store_true",
        help="Log in the AGENT session (TELEGRAM_AGENT_SESSION_PATH) — the "
             "second account that serves as the user-facing chat surface. "
             "Without this flag, the primary userbot session is logged in.",
    )
    svc = sub.add_parser(
        "service",
        help="Install/manage the macOS LaunchAgent that runs `oncall api` "
             "(or `oncall laptop-worker` with --worker).",
    )
    svc.add_argument(
        "--worker", action="store_true",
        help="Target the laptop capability worker (com.oncall.worker) instead "
             "of the orchestrator. Use on the laptop in cloud-primary mode so "
             "`oncall laptop-worker` auto-starts at login and restarts on crash.",
    )
    svc.add_argument(
        "action",
        choices=["install", "uninstall", "start", "stop", "status", "logs"],
        help=(
            "install: write LaunchAgent plist + load; "
            "uninstall: unload + remove plist; "
            "start/stop: launchctl kickstart / bootout; "
            "status: launchctl print summary; "
            "logs: tail ~/.oncall/logs/oncall.{out,err}.log"
        ),
    )
    svc.add_argument(
        "-f", "--follow", action="store_true",
        help="(logs) follow new output, like `tail -f`.",
    )
    svc.add_argument(
        "-n", "--lines", type=int, default=100,
        help="(logs) initial number of lines to show (default 100).",
    )
    args = parser.parse_args()
    if args.cmd == "init":
        _init(force=args.force)
    elif args.cmd == "api":
        _serve_api()
    elif args.cmd == "mcp":
        _serve_mcp()
    elif args.cmd == "laptop-worker":
        _serve_laptop_worker()
    elif args.cmd == "telegram-login":
        _telegram_login(
            verbose=getattr(args, "verbose", False),
            qr=getattr(args, "qr", False),
            agent=getattr(args, "agent", False),
        )
    elif args.cmd == "service":
        from . import service
        spec = service.WORKER if getattr(args, "worker", False) else service.AGENT
        fn = getattr(service, args.action)
        if args.action == "logs":
            fn(spec, follow=args.follow, lines=args.lines)
        else:
            fn(spec)
    else:
        parser.print_help()
        sys.exit(2)


if __name__ == "__main__":
    main()
