"""CLI entrypoints.

`oncall init`           → scaffold ~/.oncall/.env on first install.
`oncall api`            → run the FastAPI orchestrator + HTTP API.
`oncall mcp`            → run the stdio MCP server (spawned by `claude` as a child).
`oncall telegram-login` → one-time Telegram userbot login.
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import secrets
import sys
from pathlib import Path


_STARTER_ENV = """\
# oncall-agent config. Generated by `oncall init`.
# Project-local .env (in cwd) overrides this file if both are present.

# Orchestrator
ONCALL_TOKEN={token}
ONCALL_PORT=8765
ONCALL_DB_PATH=~/.oncall/state.db
ONCALL_PROD_HOSTS=

# Operator backend choice — see .env.example for details.
# Default uses Google AI Studio (gemini) which preserves ack-first behavior;
# set to "vercel" only if you need non-Google models via the AI Gateway.
ONCALL_OPERATOR_BACKEND=gemini
ONCALL_OPERATOR_MODEL=google/gemma-4-31b-it
ONCALL_OPERATOR_REASONING_EFFORT=minimal

# Gemini (AI Studio) — required when ONCALL_OPERATOR_BACKEND=gemini.
# Get a key at https://aistudio.google.com/apikey
GEMINI_API_KEY=

# Vercel AI Gateway — used as the operator backend when
# ONCALL_OPERATOR_BACKEND=vercel, or as the embeddings backend when
# ONCALL_MEMORY_EMBED_MODEL is a vendor-prefixed slug.
# https://vercel.com/dashboard/ai-gateway/api-keys
AI_GATEWAY_BASE_URL=https://ai-gateway.vercel.sh/v1
AI_GATEWAY_API_KEY=

# Memory embedder. Default uses local Ollama (~30× faster). Pull first:
#   ollama pull nomic-embed-text:137m-v1.5-fp16
ONCALL_MEMORY_EMBED_MODEL=nomic-embed-text:137m-v1.5-fp16
ONCALL_OLLAMA_HOST=http://localhost:11434

# Executor (Claude CLI) uses whatever auth `claude` already has on this host —
# keychain OAuth for subscription users, or ANTHROPIC_API_KEY in your shell env
# if you prefer a workspace API key. Nothing to configure here.

# Telegram BOT (optional — talk to the operator via Telegram instead of REPL).
# Uses the HTTP Bot API — only the token + your numeric user_id are needed.
# 1. Create a bot via @BotFather and paste its token here.
# 2. Get your own numeric user_id from @userinfobot and paste it as OWNER_ID.
#    Only that id can DM the bot; everyone else is silently ignored.
TELEGRAM_BOT_TOKEN=
TELEGRAM_BOT_OWNER_ID=

# Telegram USERBOT (optional, separate from the bot above — reads inbound DMs
# from arbitrary senders to the user's own account, for triage + reply-by-
# proposal). Requires registering an app at https://my.telegram.org/apps.
TELEGRAM_API_ID=
TELEGRAM_API_HASH=
TELEGRAM_SESSION_PATH=~/.oncall/telegram.session
TELEGRAM_IMPORTANT_SENDERS=
TELEGRAM_IMPORTANT_KEYWORDS=urgent,down,production,outage,critical
# Comma-separated @usernames the userbot should NEVER surface (e.g. service
# bots like @userinfobot). The own bot from TELEGRAM_BOT_TOKEN is auto-added
# at startup via its user_id; you only need this list for extra entries.
TELEGRAM_USERBOT_IGNORE_USERNAMES=
"""


def _serve_api() -> None:
    import uvicorn
    from .config import get_settings
    from .api import create_app

    settings = get_settings()
    app = create_app()
    uvicorn.run(
        app,
        host="127.0.0.1",
        port=settings.oncall_port,
        log_level="info",
        # Cap how long uvicorn waits for in-flight connections on SIGTERM
        # before force-closing them and running lifespan teardown. Without
        # this, long-lived SSE subscribers to /events block teardown
        # indefinitely — and launchd's ExitTimeOut (default 20s) then
        # escalates to SIGKILL, skipping our shutdown path. Skipping
        # shutdown leaves pending approvals UNRESOLVED in the DB and lets
        # the next daemon boot try to --resume orphan claude sessions,
        # which fails with cli_error. Capping at 5s gives uvicorn enough
        # time to drain real traffic but guarantees lifecycle.shutdown()
        # runs (it denies pending approvals + marks running tasks killed).
        timeout_graceful_shutdown=5,
    )


def _serve_mcp() -> None:
    from .mcp_server import cli_main
    cli_main()


def _init(*, force: bool = False) -> None:
    """Scaffold ~/.oncall/ with a starter .env. Safe to re-run; non-destructive."""
    config_dir = Path.home() / ".oncall"
    config_dir.mkdir(parents=True, exist_ok=True)
    env_path = config_dir / ".env"
    if env_path.exists() and not force:
        print(f"{env_path} already exists. Use --force to overwrite.")
        sys.exit(0)
    token = secrets.token_urlsafe(32)
    env_path.write_text(_STARTER_ENV.format(token=token), encoding="utf-8")
    env_path.chmod(0o600)
    print(f"Wrote {env_path} (mode 0600).")
    print("Next steps:")
    print(f"  1. Edit {env_path} — at minimum set AI_GATEWAY_API_KEY for the operator.")
    print("  2. Install Claude Code: https://docs.claude.com/en/docs/claude-code")
    print("  3. (Optional) `oncall telegram-login` to enable Telegram.")
    print("  4. `oncall api` to run the orchestrator.")


def _telegram_login(*, verbose: bool = False, qr: bool = False) -> None:
    from .config import get_settings
    from .telegram_service import login_interactive, login_qr_interactive

    s = get_settings()
    if not (s.telegram_api_id and s.telegram_api_hash):
        print("ERROR: set TELEGRAM_API_ID and TELEGRAM_API_HASH in .env first.", file=sys.stderr)
        print("  Get them at https://my.telegram.org/apps", file=sys.stderr)
        sys.exit(2)
    logging.getLogger("telethon").setLevel(logging.DEBUG if verbose else logging.INFO)
    runner = login_qr_interactive if qr else login_interactive
    asyncio.run(runner(
        api_id=int(s.telegram_api_id),
        api_hash=s.telegram_api_hash,
        session_path=s.telegram_session_path,
    ))
    print()
    print(f"Session written to {s.telegram_session_path}.")
    print()
    print("Next: the userbot only attaches at daemon startup, so restart to pick up the new session:")
    print("  oncall service stop && oncall service start    (LaunchAgent)")
    print("  oncall api                                     (foreground / dev)")


def _configure_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    # Telethon is verbose at INFO — keep at WARNING unless explicitly opted in.
    logging.getLogger("telethon").setLevel(logging.WARNING)
    # SQLAlchemy / httpx are fine at WARNING too.
    logging.getLogger("httpx").setLevel(logging.WARNING)


def main() -> None:
    _configure_logging()
    parser = argparse.ArgumentParser(prog="oncall")
    sub = parser.add_subparsers(dest="cmd", required=True)
    init_p = sub.add_parser("init", help="Scaffold ~/.oncall/.env (run this first).")
    init_p.add_argument("--force", action="store_true",
                        help="Overwrite an existing ~/.oncall/.env.")
    sub.add_parser("api", help="Run the orchestrator HTTP API")
    sub.add_parser("mcp", help="Run the stdio MCP server (used by claude subprocesses)")
    tg_login_p = sub.add_parser(
        "telegram-login",
        help="One-time interactive Telegram userbot login (writes session file).",
    )
    tg_login_p.add_argument(
        "-v", "--verbose", action="store_true",
        help="Show telethon DEBUG logs (every MTProto frame) for troubleshooting.",
    )
    tg_login_p.add_argument(
        "--qr", action="store_true",
        help="Login via QR code instead of phone+code. Scan from an already-"
             "logged-in Telegram app (Settings → Devices → Link Desktop Device).",
    )
    svc = sub.add_parser(
        "service",
        help="Install/manage the macOS LaunchAgent that runs `oncall api`.",
    )
    svc.add_argument(
        "action",
        choices=["install", "uninstall", "start", "stop", "status", "logs"],
        help=(
            "install: write LaunchAgent plist + load; "
            "uninstall: unload + remove plist; "
            "start/stop: launchctl kickstart / bootout; "
            "status: launchctl print summary; "
            "logs: tail ~/.oncall/logs/oncall.{out,err}.log"
        ),
    )
    svc.add_argument(
        "-f", "--follow", action="store_true",
        help="(logs) follow new output, like `tail -f`.",
    )
    svc.add_argument(
        "-n", "--lines", type=int, default=100,
        help="(logs) initial number of lines to show (default 100).",
    )
    args = parser.parse_args()
    if args.cmd == "init":
        _init(force=args.force)
    elif args.cmd == "api":
        _serve_api()
    elif args.cmd == "mcp":
        _serve_mcp()
    elif args.cmd == "telegram-login":
        _telegram_login(
            verbose=getattr(args, "verbose", False),
            qr=getattr(args, "qr", False),
        )
    elif args.cmd == "service":
        from . import service
        fn = getattr(service, args.action)
        if args.action == "logs":
            fn(follow=args.follow, lines=args.lines)
        else:
            fn()
    else:
        parser.print_help()
        sys.exit(2)


if __name__ == "__main__":
    main()
